
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # Assign a reviewer for the PRs
    reviewers:
      - "project-admin" # Replace with actual GitHub username or team
    # Add a label to the PRs
    labels:
      - "dependencies"
      - "automated"
    # Enable auto-merging for patch updates to ensure security fixes are applied quickly.
    automerge: true
    allow:
      # Allow auto-merging for patch-level updates
      - dependency-type: "direct"
        update-types: ["patch"]
      - dependency-type: "indirect"
        update-types: ["patch"]
    # Group patch and minor updates into a single PR for easier management.
    # Major updates will still get their own PRs.
    groups:
      all-minor-and-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "project-admin"
    labels:
      - "ci"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
