version: '3.8'

services:
  app:
    build: .
    ports:
      - "9002:9002"
      - "8080:8080" # Firestore Emulator
      - "4000:4000" # Emulator UI
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # Pass environment variables needed by the application
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    # Keep the service running in dev mode
    command: npm run dev
