
// scripts/generate-tests.js
const { ai } = require('@/ai/genkit');
const fs = require('fs');
const path = require('path');

// This is a simplified placeholder. In a real-world scenario, you might have a more robust
// way to configure and call the Genkit AI object from a script.
// For this example, we assume it's configured and can be used directly.

async function generateTestsForFeature(featureName, description) {
  console.log(`🤖 Generating tests for feature: ${featureName}...`);
  const prompt = `
Generate a complete Jest unit test file in TypeScript for the following feature.
The feature name is "${featureName}".
The feature description is: "${description}"

Follow these rules strictly:
1.  The code must be a single, complete file.
2.  Use Jest for testing ('describe', 'it', 'expect').
3.  Mock any external dependencies like database calls or other services.
4.  Include at least 3 test cases: a success case, a failure case, and an edge case.
5.  Do not include any explanations, comments, or markdown formatting. Output only the raw TypeScript code for the test file.

Start the file with a comment indicating it was auto-generated.
`;

  try {
    const { text } = await ai.generate({
        prompt: prompt,
        model: 'googleai/gemini-1.5-pro-latest',
        config: { temperature: 0.3 },
    });
    
    if (!text) {
        throw new Error('AI did not return any text.');
    }

    const cleanedCode = text.replace(/```typescript\n/g, '').replace(/```/g, '').trim();

    const fileName = `${featureName.toLowerCase().replace(/\s+/g, '-')}.test.ts`;
    const filePath = path.join(__dirname, '..', 'tests', 'unit', fileName);
    
    fs.writeFileSync(filePath, `// Auto-generated by CrewSphere's AI Test Generator\n\n` + cleanedCode);
    console.log(`✅ Successfully generated test file: ${filePath}`);

  } catch (error) {
    console.error(`❌ Failed to generate tests for ${featureName}:`, error);
  }
}

async function main() {
    console.log("--- Starting AI Test Generation ---");
    
    // Example call for a new or updated feature
    await generateTestsForFeature(
      'Flight Swap Conflict Detection',
      'When a crew member requests a flight swap, the system checks their rest hours and upcoming flights for any conflicts. If a conflict is detected, it blocks the swap and may recommend an alternative crew member.'
    );

    await generateTestsForFeature(
      'AI Report Summarization',
      'When a purser submits a free-text flight report, the AI extracts 3 key risks, any behavioral patterns, and one recommendation. The output must be a structured JSON object: { risks: string[], recommendations: string[] }.'
    );

    console.log("--- AI Test Generation Complete ---");
}

main();
