
name: Full Test Suite — CrewSphere
on:
  push:
    branches: [ main ]
  pull_request_target:
    types: [ opened, synchronize, reopened ]
  schedule:
    # Run every 3 days for proactive code audits
    - cron: '0 3 */3 * *'

jobs:
  test-all:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # For pull_request_target, we need to checkout the specific PR commit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Security Audit
        run: npm audit --audit-level=high

      - name: Run Next.js Code Quality Audit
        id: audit
        run: npm run audit

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Full Test Suite
        run: npm test
        env:
            NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            
      - name: Run Performance Tests (Lighthouse)
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.github/lighthouse-ci.config.js'
          uploadArtifacts: true
          temporaryPublicStorage: true
      
      - name: Generate New Tests on Feature Commits
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'feat:')
        run: npm run test:auto-generate
        env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit Generated Tests
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'feat:')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tests/unit/*.test.ts
          # Use 'git commit' with '|| echo' to prevent failure if there are no changes
          git commit -m "🤖 Auto-generated tests for new feature" || echo "No new tests to commit."
          git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Upload Test Reports
        if: always() # Always run this step to upload reports even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            playwright-report/
            lighthouse-report.html
            *.json
          retention-days: 7

  deploy-to-firebase:
    name: 🚀 Deploy to Firebase Hosting
    needs: test-all
    runs-on: ubuntu-latest
    # Only run on pushes to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js App
        run: npm run build
        env:
            NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AIRCREW_HUB }}'
          channelId: live
          projectId: aircrew-hub
          target: aircrew-hub-68d34

  auto-optimize-and-pr:
    name: 🤖 AI Auto-Optimization
    needs: test-all
    runs-on: ubuntu-latest
    # Only run this job after a successful push to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      
      - name: Run Predictive Analysis
        id: analysis
        run: npm run auto-optimize
        env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            
      - name: Apply Optimizations to Code
        id: apply
        run: node src/scripts/apply-optimizations.js
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: ✨ AI-suggested rule optimizations"
          branch: "feature/ai-optimizations"
          delete-branch: true
          title: "🤖 AI-Suggested Alert Rule Optimizations"
          body: |
            ## Auto-Optimization Report
            
            This pull request was automatically generated by the CrewSphere AI analysis service.
            
            Based on a 90-day performance review of our alert system, the following optimizations are recommended to improve signal-to-noise ratio and proactive detection.
            
            Please review the changes in `src/lib/alert-rules.ts` and merge if they align with our operational goals.
            
            ---
            *This is an automated PR. No human intervention was required to generate this code.*
          labels: "ai, enhancement, automated"
          reviewers: "project-admin" # Replace with actual GitHub usernames
          assignees: "project-admin"

  proactive-code-audit:
    name: 🤖 AI Proactive Code Audit
    runs-on: ubuntu-latest
    # Run on a schedule
    if: github.event_name == 'schedule'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Proactive AI Code Audit
        id: audit
        run: npm run audit:ai
        env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
            GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
            GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create Pull Request for AI Refactoring
        if: steps.audit.outputs.pr_title # Check if a PR title was outputted
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "refactor: ✨ AI-suggested code quality improvements"
          branch: "feature/ai-refactor-${{ github.run_id }}"
          delete-branch: true
          title: "🤖 ${{ steps.audit.outputs.pr_title }}"
          body: |
            ## Proactive Code Quality Audit
            
            This pull request was automatically generated by the CrewSphere Watchdog agent.
            
            ${{ steps.audit.outputs.pr_body }}
            
            **Analysis ID:** `${{ steps.audit.outputs.analysis_id }}`
            
            ---
            *This is an automated PR. No human intervention was required to generate this code.*
          labels: "ai, refactor, automated, enhancement"
          reviewers: "project-admin"
          assignees: "project-admin"
